name: example
version: '${version}'
description: Example plugin for Paper
website: https://github.com/PleahMaCaka/paper-template
authors:
  - PleahMaCaka
main: io.github.pleahmacaka.example.Example
api-version: '1.20'
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.0
  - org.jetbrains.kotlin:kotlin-reflect:1.9.0
