name: ExamplePlugin
author: PaperMC
description: An example plugin
website: https://github.com/
version: '${version}'
main: example.ExamplePlugin
api-version: 1.19
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.20
  - org.jetbrains.kotlin:kotlin-reflect:1.7.20
